config/routes.rb
Rails.application.routes.draw do
  get 'reviews/index'

  resources :categories, only: [:index] do
    resources :books
  end

  resources :books do
    resources :reviews, only: [:index, :new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  replicated_model
  mount_uploader :cover_image, CoverImageUploader
  belongs_to :category
  acts_as_list scope: :category
  has_many :reviews, dependent: :destroy
  # before_save :set_cover_image
  def img_cat
    ["nightlife", "city", "people", "transport", "business"].sample
  end

  def is_best_seller?
    position < 11
  end

  def set_cover_image
    if self.cover_image.blank?
      thumb_url = BingSearch.get_image_url(self.title)[:thumbnail_url]
      self.remote_cover_image_url = thumb_url
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  replicated_model
  has_many :books, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @books = @category.books.page(params[:page])
    @best_sellers = @books.limit(5)
    @on_sale = @books.order("price asc").limit(5)
  end

  def show
    @category = Category.find(params[:category_id])
    @book = @category.books.find(params[:id])
    @similar_books = @category.books.order("RAND()").where.not(id: @book.id).limit(5)
    @recent_reviews = @book.reviews.order('created_at desc').limit(10)
    @also_viewed_books = @category.books.order("RAND()").where.not(id: @similar_books.ids).limit(5)
  end
  def random
    @book = Book.order("RAND()").first
    @books = Book.order("RAND()").limit(3)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.order('name asc')
    @top_categories = Category.all.limit(15)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @book = Book.find(params[:book_id])
    @reviews = Review.where(book_id: params[:book_id]).order(created_at: :desc).page(params[:page]).per(5)
  end

  def new
    @book = Book.find(params[:book_id])
    @review = @book.reviews.new
  end

  def create
    @book = Book.find(params[:book_id])
    @review = @book.reviews.new(review_params)
    @review.rating = rand(1..5)
    @review.reviewer_name = FFaker::Name.name
    if @review.save
      redirect_to category_book_url(@book.category, @book), notice: "Thanks #{@review.reviewer_name}! Review Submitted!"
    end
  end

  private

  def review_params
    params.require(:review).permit(:review)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def random_publication
    FFaker::AddressUS.city + " " + ["Times", "Post", "Citizen Enquirer", "Post-Gazette"].sample
  end
  def random_adj
    ["riveting","heartwarming","intense", "extreme", "impassioned"].sample
  end
  def random_desc(sentences = 2)
    markov = MarkyMarkov::Dictionary.new('dictionary')
    markov.parse_file(File.join(Rails.root,'lib','dict.txt'))
    markov.generate_n_sentences sentences
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_book.html.slim
.column
  =link_to category_book_path(book.category, book), class: '' do
    .image
      img src=book.cover_image.book
    .header= book.title
  .row
    .ui.star.rating data-max-rating='5' data-rating=book.reviews.average(:rating).to_i
    i= "(" + book.reviews.count.to_s + ")"
  = number_to_currency book.price

app/views/books/index.html.slim
.ui.container.grid
  .row
    .ui.breadcrumb
      = link_to "Home", categories_path, class: 'section'
      .divider 
        | / 
      .section Category
  .row
    h1.yellow= @category.name
  - unless params[:page].present?
    .row
      h3 Best Sellers
    .row
      .ui.five.column.grid
        = render @best_sellers

    .row
      h3 Bargain Bin!
    .row
      .ui.five.column.grid
        = render @on_sale
  .row
    .ui.five.column.grid
      =render @books
      = paginate @books

app/views/books/random.html.slim
.ui.container.grid
  .row
    .ui.breadcrumb
      = link_to "Home", root_path, class: 'section'
      .divider 
        | / 
      .section Category: #{@book.category.name}
  .row
    h1= @book.title
  .row
    img src="http://via.placeholder.com/250x150"
  .row
    h3 From #{random_publication} bestselling author #{@book.author} comes a #{random_adj} story about #{FFaker::HipsterIpsum.words.to_sentence} -- perfect for fans of #{ FFaker::Book.author }, #{ FFaker::Book.author }, and #{ FFaker::Book.author }.
  .row
    .ui.orange.label Top #{@book.position} Release!
  .row
    h5 Description
    p #{random_desc(8)}
  .row
    h5 ©2018 #{@book.author}
  .ui.horizontal.divider
    h3 Customers also bought...
  .row
    .ui.cards
      = render @books
  
  .ui.horizontal.divider
    h3 Customer REviews

app/views/books/show.html.slim
.ui.container.grid
  - if notice
    .row
      .ten.wide.centered.column
        .ui.icon.positive.message
          i.icon.checkmark
          .content
            .header
              Review Accepted!
            p= notice
  .row
    .ui.breadcrumb
      = link_to "Home", categories_path, class: 'section'
      .divider 
        | / 
      .section
      = link_to "Category: #{@book.category.name}", category_books_path(@book.category)
      .divider
        | /
      .section= @book.title
  .row
    .ui.grid
      .four.wide.column
        .ui.card
          .image
            = image_tag @book.cover_image.book
      .eight.wide.column
        .row
          h1= @book.title
        .row
          h5 by #{@book.author}
        .row
          .ui.star.rating data-max-rating='5' data-rating=@book.reviews.average(:rating).to_i
          b #{@book.reviews.count} reviews
        .row
          br
          br
          br
          h3 From #{random_publication} bestselling author #{@book.author} comes a #{random_adj} story about #{FFaker::HipsterIpsum.words.to_sentence} -- perfect for fans of #{ FFaker::Book.author }, #{ FFaker::Book.author }, and #{ FFaker::Book.author }.
        .row
          h4 ##{@book.position} in #{@book.category.name }!
        .row
          h5 Description
          p #{random_desc(8)}
        .row
          h5 ©2018 #{@book.author}
      .four.wide.column
        .ui.segments
          .ui.segment
            h3 Your Price: #{number_to_currency(@book.price)}
            h3 Out of Stock
            p We're sorry, this book has been so popular we've temporarily out of stock of it. 
            p Check back again soon for updates!
          .ui.segment
            h3 Write a review!
            p Write a review and let people know your opinion!
            = link_to "Write Review", new_book_review_path(@book), class: 'ui orange button'
  .ui.horizontal.divider
    h3 Frequently Purchased With
  .row
    .ui.five.column.grid
      = render @similar_books
  
  .ui.horizontal.divider
    h3 Customer Buzz
  .row
    .twelve.wide.column
      h3 Recent Customer Reviews
      .row
        .ui.comments.fluid
          = render @recent_reviews
      - if @book.reviews.count > 10
        .row
          = link_to book_reviews_path(@book) do
            h3 See all Reviews...
    .four.wide.column
      h3 Customers Also Viewed...
      .ui.one.column.grid
        = render @also_viewed_books
      

app/views/categories/_category.html.slim
= link_to category_books_path(category), class: "statistic #{category.color}" do
  .value
    i class="icon #{category.icon}"
  .label
    = category.name

app/views/categories/index.html.slim
.ui.container.grid
  .ui.horizontal.divider
    h1 Books at Bookazon
.ui.grid
  .row
    .three.wide.column
      .ui.vertical.menu
        .item
          .header Top Categories
          .menu
            - @top_categories.each do |cat|
              = link_to cat.name, category_books_path(cat), class: "item"

            
    .thirteen.wide.column
      .row
        h1 Recommended categories for you...
      .row
        .ui.horizontal.divider
      .row
        .ui.five.statistics
          - @categories.sample(5).each do |cat|
            = render cat
      .row
        .ui.horizontal.divider
          h1 All Categories
      .row
        .ui.five.statistics
          = render @categories

app/views/layouts/application.html.slim
doctype html
html
  head
    title Bookazon
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    .ui.top.inverted.blue.menu
      .header.item Bookazon
      = link_to "Books", categories_path, class: 'item'
    = yield 

app/views/reviews/_review.html.slim
.comment
  .content
    a.author #{review.reviewer_name}
    .metadata
      .ui.star.rating data-max-rating='5' data-rating=review.rating
      p  #{time_ago_in_words(review.created_at)} ago
    .text
      p #{review.review}

app/views/reviews/index.html.slim
.ui.container.grid
  .row
    .ui.breadcrumb
      = link_to "Home", categories_path, class: 'section'
      .divider 
        | / 
      .section
      = link_to "Category: #{@book.category.name}", category_books_path(@book.category)
      .divider
        | /
      .section
        = link_to @book.title, category_book_path(@book.category, @book)
      .divider
        | /
      .section All Customer Reviews
  .row
    .ui.grid
      .four.wide.column
        .ui.card
          .image
            = image_tag @book.cover_image.book
      .eight.wide.column
        .row
          h1= @book.title
        .row
          h5 by #{@book.author}
        .row
          .ui.star.rating data-max-rating='5' data-rating=@book.reviews.average(:rating).to_i
          b #{@book.reviews.count} reviews
      .four.wide.column
        .ui.segment
          h3 Your Price: #{number_to_currency(@book.price)}
          h3 Out of Stock
          p We're sorry, this book has been so popular we've temporarily out of stock of it. 
          p Check back again soon for updates!
.ui.container.grid
  .row
    .sixteen.wide.column
      .ui.comments
        = render @reviews
  .row
    .sixteen.wide.column
      = paginate @reviews

app/views/reviews/new.html.slim
.ui.container.grid
  .row
    .sixteen.wide.column
      .ui.breadcrumb
        = link_to "Home", categories_path, class: 'section'
        .divider 
          | / 
        .section
        = link_to "Category: #{@book.category.name}", category_books_path(@book.category)
        .divider
          | /
        .section
        = link_to @book.title, category_book_path(@book.category, @book)
        .divider
          | /
        .section= "New Review"
  .row
    .sixteen.wide.column
      h1 Reviewing #{@book.title}
    .sixteen.wide.column
      h5 By #{@book.author}
  .row
    .sixteen.wide.column
      = form_for([@book, @review], html: {class: 'ui form'}) do |f|
        = f.text_area :review
        = f.submit "Submit Review", class: 'ui button'